//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelDbFirst.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perdb2Entities : DbContext
    {
        public perdb2Entities()
            : base("name=perdb2Entities")
        {
            Configuration.LazyLoadingEnabled = false;      //İkisi birlikte bağlantıların (virtual olanlar) otomatik yüklenmesini engeller
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Ulke> Ulke { get; set; }
        public virtual DbSet<Unvan> Unvan { get; set; }
    }
}
