//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelDbFirst.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Personel1 = new HashSet<Personel>();
        }
    
        public int PersonelId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<int> UnvanId { get; set; }
        public string UlkeId { get; set; }
        public string UyrukId { get; set; }
        public Nullable<int> YoneticiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personel> Personel1 { get; set; }
        public virtual Personel Personel2 { get; set; }
        public virtual Ulke Ulke { get; set; }
        public virtual Ulke Ulke1 { get; set; }
        public virtual Unvan Unvan { get; set; }
    }
}
